spring:
  datasource:
    url: jdbc:mysql://alicloud:3306/mybatis?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456Ben
    driver-class-name: com.mysql.cj.jdbc.Driver

    # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      filters: stat,wall  # 底层开启功能，stat（sql监控），wall（防火墙）
      filter:             # 对上面filters里面的stat的详细配置
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

      stat-view-servlet:
        enabled: true
      #        login-username: admin
      #        login-password: password

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      aop-patterns: com.knight.boot.*


