package com.knight.dao;

import com.knight.bean.Cat;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    int insert(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    Cat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    List<Cat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    int updateByPrimaryKey(Cat record);

    // 批量插入
    void insertBatch(@Param("cats") List<Cat> cats);
}