package com.knight.bean;

public class Cat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.id
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.cName
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.cAge
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    private Integer cage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.c_gender
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    private Integer cGender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.id
     *
     * @return the value of t_cat.id
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.id
     *
     * @param id the value for t_cat.id
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.cName
     *
     * @return the value of t_cat.cName
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.cName
     *
     * @param cname the value for t_cat.cName
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.cAge
     *
     * @return the value of t_cat.cAge
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    public Integer getCage() {
        return cage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.cAge
     *
     * @param cage the value for t_cat.cAge
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    public void setCage(Integer cage) {
        this.cage = cage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.c_gender
     *
     * @return the value of t_cat.c_gender
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    public Integer getcGender() {
        return cGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.c_gender
     *
     * @param cGender the value for t_cat.c_gender
     *
     * @mbg.generated Tue May 17 14:14:50 CST 2022
     */
    public void setcGender(Integer cGender) {
        this.cGender = cGender;
    }

    @Override
    public String toString() {
        return "Cat{" +
                "id=" + id +
                ", cname='" + cname + '\'' +
                ", cage=" + cage +
                ", cGender=" + cGender +
                '}';
    }
}