# yaml表示以上对象
person:
  #  字符串无需加引号，如果要加，''会将 \n 作为字符串输出，""会将 \n 作为换行输出
  #  userName: 张三 \n 李四
  #  userName: '张三 \n 李四'
  userName: "张三 \n 李四"
  boss: false
  birth: 2019/12/12 20:12:33
  age: 18
  pet:
    name: tomcat
    weight: 23.4
  interests: [ 篮球,游泳 ]
  animal:
    - jerry
    - mario
  score:
    english:
      first: 30
      second: 40
      third: 50
    math: [ 131,140,148 ]
    chinese: { first: 128,second: 136 }
  salarys: [ 3999,4999.98, 5999.99 ]
  allPets:
    sick:
      - { name: tom }
      - { name: jerry,weight: 47 }
    health: [ { name: mario,weight: 47 } ]